plugins:
  - rubocop-sequel
  - rubocop-rspec
  - rubocop-performance


Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Sequel/ConcurrentIndex:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/DescribeClass:
  Enabled: false

AllCops:
    NewCops: enable