services:

  db:
    image: ${DB_CONTAINER_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGSSLMODE: disable
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  app:
    image: app:latest
    container_name: klimt-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MAX_CONNECTIONS: 5
      DB_POOL_TIMEOUT: 5
      RACK_ENV: ${RACK_ENV:-development}
    ports:
      - "4567:4567"
    volumes:
      - .:/app
      - ./tmp:/app/tmp
    networks:
      - network

  adminer:
    image: adminer
    container_name: klimt-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pappu687
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge